/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vitas;

import cl.programacion.avanzada.datos.AccesoDatosImpl;
import cl.programacion.avanzada.excepciones.AccesoDatosEx;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class Menu extends javax.swing.JFrame {
    
    private static final String nombreArchivo = "C:\\Users\\usuario\\Desktop\\LaboratorioFinalSwing\\CatalogoPelicula\\peliculas.txt";
    
    AccesoDatosImpl iniciarCatalogo = new AccesoDatosImpl();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        itemMenuIniciarCatalogo = new javax.swing.JMenuItem();
        itemMenuAgregarPelicula = new javax.swing.JMenuItem();
        itemMenuListarPeliculas = new javax.swing.JMenuItem();
        itemMenuBuscarPeliculas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuPrincipal.setText("Mantenedor De Pelicula");

        itemMenuIniciarCatalogo.setText("Iniciar Catalogo De Pelicula");
        itemMenuIniciarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuIniciarCatalogoActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(itemMenuIniciarCatalogo);

        itemMenuAgregarPelicula.setText("Agregar Pelicula");
        itemMenuAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAgregarPeliculaActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(itemMenuAgregarPelicula);

        itemMenuListarPeliculas.setText("Listar Peliculas");
        itemMenuListarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuListarPeliculasActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(itemMenuListarPeliculas);

        itemMenuBuscarPeliculas.setText("Buscar Peliculas");
        itemMenuBuscarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuBuscarPeliculasActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(itemMenuBuscarPeliculas);

        jMenuBar1.add(jMenuPrincipal);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuIniciarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuIniciarCatalogoActionPerformed
        
        try {
            // TODO add your handling code here:                 
            //Llamamos a sus Metodos         
            
            if(iniciarCatalogo.existe(nombreArchivo)){
                JOptionPane.showMessageDialog(null, "El Archivo ya existe");
            }else{
                iniciarCatalogo.crear(nombreArchivo); 
            }
        } catch (AccesoDatosEx ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemMenuIniciarCatalogoActionPerformed

    private void itemMenuAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAgregarPeliculaActionPerformed
        // TODO add your handling code here:
        new AgregarPelicula().setVisible(true);
    }//GEN-LAST:event_itemMenuAgregarPeliculaActionPerformed

    private void itemMenuListarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuListarPeliculasActionPerformed
        // TODO add your handling code here:
        new ListarPeliculas().setVisible(true);
    }//GEN-LAST:event_itemMenuListarPeliculasActionPerformed

    private void itemMenuBuscarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuBuscarPeliculasActionPerformed
        // TODO add your handling code here:
        new BuscarPelicula().setVisible(true);
    }//GEN-LAST:event_itemMenuBuscarPeliculasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuAgregarPelicula;
    private javax.swing.JMenuItem itemMenuBuscarPeliculas;
    private javax.swing.JMenuItem itemMenuIniciarCatalogo;
    private javax.swing.JMenuItem itemMenuListarPeliculas;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
